#
# Copyright (C) 2024 nosignals
#
name: ULO Autobuilder

on:
  push:
    branches:
    - main

jobs: 
  build_ipk:
    permissions:
      contents: write
    strategy:
      matrix:
        kernel: [4.9.337, 6.1.66, 6.6.6]
    name: Build IPK Files
    runs-on: ubuntu-latest
    steps:
      
      - name: Cleanup and Installing Prerequisites
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E apt-get update
          sudo -E apt-get -y install lolcat
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
                    
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Building OpenWrt
        run: |
          sudo ./ulo -k ${{ matrix.kernel }} -m s905x -s 512
          
      - name: Creating Package Artifact
        run: |
          mkdir -p ./artifact/output
          cp -rf ./out ./artifact
          
      - name: Delivering Package
        uses: actions/upload-artifact@v2
        with:
          name: openwrt_package
          path: ./artifact
