#
# Copyright (C) 2024 nosignals
#
name: ULO Autobuilder

on:
  push:
    branches:
    - main

jobs: 
  build_ipk:
    permissions:
      contents: write
    strategy:
      matrix:
        kernel: [4.9.337, 6.1.66, 6.6.6]
        devices: [s905x, s905x2, s905x3, s905x4]
    name: ULO Autobuilder
    runs-on: ubuntu-latest
    steps:
      
      - name: Cleanup and Installing Prerequisites
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E apt-get update
          sudo -E apt-get -y install lolcat build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
                    
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Building OpenWrt
        run: |
          sudo ./ulo -k ${{ matrix.kernel }} -m ${{ matrix.devices }} -s 512
          
      - name: Creating Package Artifact
        run: |
          mkdir -p ./artifact
          cp -rf ./out/${{ matrix.devices }}/* ./artifact/
          
      - name: Delivering Package
        uses: actions/upload-artifact@v2
        with:
          name: openwrt_package
          path: ./artifact/*
          
      - name: Creating Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.devices }}
          release_name: Release ${{ matrix.devices }}
          file: ./artifact/*
          body: |
            Openwrt Build
          draft: false
          prerelease: false
          
